DROP TABLE IF EXISTS sacas_distribucion CASCADE;
DROP TABLE IF EXISTS clientes_telefono CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS despachos CASCADE;
DROP TABLE IF EXISTS distribuidores CASCADE;
